-- MySQL Script generated by MySQL Workbench
-- Wed May 16 23:28:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CasesInOrder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CasesInOrder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CasesInOrder` DEFAULT CHARACTER SET utf8 ;
USE `CasesInOrder` ;

-- -----------------------------------------------------
-- Table `CasesInOrder`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasesInOrder`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(65) NOT NULL,
  `user_password` VARCHAR(255) NOT NULL,
  `user_email` VARCHAR(65) NOT NULL,
  `user_contacts` VARCHAR(255) NULL,
  `user_registration` TIMESTAMP NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `id_users_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CasesInOrder`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasesInOrder`.`projects` (
  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`project_id`, `user_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC),
  INDEX `fk_projects_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `project_name_UNIQUE` (`project_name` ASC),
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `CasesInOrder`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CasesInOrder`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasesInOrder`.`tasks` (
  `task_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(255) NOT NULL,
  `task_create_date` TIMESTAMP NOT NULL,
  `task_complete_date` TIMESTAMP NULL,
  `task_deadline` TIMESTAMP NULL,
  `task_link_file` VARCHAR(255) NULL,
  `project_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`task_id`, `project_id`, `user_id`),
  UNIQUE INDEX `task_name_UNIQUE` (`task_name` ASC),
  UNIQUE INDEX `task_id_UNIQUE` (`task_id` ASC),
  INDEX `fk_tasks_projects1_idx` (`project_id` ASC),
  INDEX `fk_tasks_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `CasesInOrder`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `CasesInOrder`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
