-- MySQL Script generated by MySQL Workbench
-- Wed May 16 23:28:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema doings_done
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema doings_done
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `doings_done` DEFAULT CHARACTER SET utf8 ;
USE `doings_done` ;

-- -----------------------------------------------------
-- Table `doings_done`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doings_done`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `contacts` VARCHAR(255) NULL,
  `registration` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doings_done`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doings_done`.`projects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_projects_users1_idx` (`user_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `doings_done`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `doings_done`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `doings_done`.`tasks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `create_date` TIMESTAMP NOT NULL,
  `complete_date` TIMESTAMP NULL,
  `deadline` TIMESTAMP NULL,
  `file` VARCHAR(255) NULL,
  `project_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_tasks_projects1_idx` (`project_id` ASC),
  INDEX `fk_tasks_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `doings_done`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tasks_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `doings_done`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
